apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Webxspark/k8s-wp'
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: allan
  syncPolicy:
    automated:
      prune: true      # Deletes resources in K8s if removed from Git
      selfHeal: true   # Automatically fixes drift/manual kubectl changes!
    syncOptions:
      - CreateNamespace=true
