apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storageSize | default "2Gi" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-pass
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.dbSecret.database | quote }}
        - name: MYSQL_USER
          value: {{ .Values.dbSecret.user | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-pass
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: {{ .Release.Name }}-mysql
  clusterIP: None
