{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-wordpress-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "nginx" | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-wordpress-service
            port:
              number: {{ .Values.wordpress.service.port | default 80 }}
{{- end }}
