apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-pass
type: Opaque
stringData:
  mysql-root-password: {{ .Values.dbSecret.rootPassword | quote }}
  mysql-password: {{ .Values.dbSecret.userPassword | quote }}
